/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
      extend: {
          "colors": {
              "surface-container-lowest": "#0e0e10",
              "accent-copper": "#B87333",
              "surface-bright": "#39393b",
              "on-tertiary-fixed-variant": "#6d3a00",
              "secondary": "#ffb693",
              "outline-variant": "#4d4635",
              "on-surface-variant": "#d0c5af",
              "surface-container-low": "#1c1b1d",
              "tertiary-fixed": "#ffdcc2",
              "on-primary-fixed": "#241a00",
              "surface-dim": "#131315",
              "inverse-primary": "#735c00",
              "on-error-container": "#ffdad6",
              "on-secondary-fixed": "#351000",
              "surface": "#131315",
              "error": "#ffb4ab",
              "surface-charcoal": "#18181B",
              "on-secondary-container": "#4b1b00",
              "on-tertiary-fixed": "#2e1500",
              "background": "#131315",
              "surface-variant": "#353437",
              "error-container": "#93000a",
              "on-tertiary-container": "#6b3800",
              "on-tertiary": "#4d2700",
              "tertiary": "#ffc392",
              "typography-high": "#FFFFFF",
              "primary-fixed-dim": "#e9c349",
              "accent-gold": "#D4AF37",
              "on-primary-fixed-variant": "#574500",
              "tertiary-container": "#f0a25d",
              "on-background": "#e5e1e4",
              "surface-container-highest": "#353437",
              "on-secondary-fixed-variant": "#7a3000",
              "primary-fixed": "#ffe088",
              "surface-tint": "#e9c349",
              "inverse-on-surface": "#313032",
              "secondary-fixed": "#ffdbcc",
              "surface-container-high": "#2a2a2c",
              "secondary-fixed-dim": "#ffb693",
              "on-surface": "#e5e1e4",
              "outline": "#99907c",
              "background-deep": "#09090B",
              "on-primary-container": "#554300",
              "primary-container": "#d4af37",
              "on-secondary": "#562000",
              "primary": "#f2ca50",
              "on-error": "#690005",
              "secondary-container": "#ea6b1e",
              "surface-container": "#201f22",
              "on-primary": "#3c2f00",
              "typography-muted": "#A1A1AA",
              "inverse-surface": "#e5e1e4",
              "tertiary-fixed-dim": "#ffb77b",
              "accent-terracotta": "#CC5500"
          },
          "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
          },
          "spacing": {
              "stack-xl": "80px",
              "container-max": "1280px",
              "gutter": "24px",
              "margin-mobile": "16px",
              "stack-md": "24px",
              "stack-sm": "8px",
              "stack-lg": "48px",
              "margin-desktop": "64px",
              "base": "8px"
          },
          "fontFamily": {
              "body-md": ["Manrope"],
              "button-text": ["Manrope"],
              "body-lg": ["Manrope"],
              "headline-xl": ["EB Garamond"],
              "headline-xl-mobile": ["EB Garamond"],
              "headline-md": ["EB Garamond"],
              "headline-lg": ["EB Garamond"],
              "label-caps": ["Manrope"]
          },
          "fontSize": {
              "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
              "button-text": ["14px", {"lineHeight": "20px", "fontWeight": "600"}],
              "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
              "headline-xl": ["64px", {"lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
              "headline-xl-mobile": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
              "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "500"}],
              "headline-lg": ["40px", {"lineHeight": "48px", "fontWeight": "500"}],
              "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "700"}]
          }
      }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
